server:
  port: 8080

spring:
  application:
    name: Pebblely App
  main:
    allow-bean-definition-overriding: true
  servlet.multipart:
    max-file-size: 1GB
    max-request-size: 1GB
  jackson:
    date-format: yyyy-MM-dd
    property-naming-strategy: SNAKE_CASE
  mvc:
    format:
      date: yyyy-MM-dd
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

## Feign configuration
feign.client.config.default:
  connectTimeout: 5000
  readTimeout: 60000
  loggerLevel: FULL

logging:
  pattern:
    console: '%clr(TRACE_ID: %X{AWS-XRAY-TRACE-ID}) %clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd
            HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta}
            %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}
            %clr(:){faint} %X{AWS-XRAY-TRACE-ID} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'
